/*
 * ==========================================
 * |          GENERATED BY SUPAZOD          |
 * ==========================================
 */

import { z } from "zod";
type JsonValue = string | number | boolean | null | { [key: string]: JsonValue | undefined } | JsonValue[];

export const jsonSchema: z.ZodType<JsonValue> = z.lazy(() =>
  z
    .union([
      z.string(),
      z.number(),
      z.boolean(),
      z.record(z.string(), z.union([jsonSchema, z.undefined()])),
      z.array(jsonSchema),
    ])
    .nullable(),
);

export const publicAiReportsRowSchema = z.object({
  created_at: z.string().nullable(),
  emergency_id: z.string().nullable(),
  id: z.string(),
  preparation_checklist: jsonSchema.nullable(),
  risk_score: z.number().nullable(),
  summary: z.string().nullable(),
  triage_level: z.string().nullable(),
});

export const publicAiReportsInsertSchema = z.object({
  created_at: z.string().optional().nullable(),
  emergency_id: z.string().optional().nullable(),
  id: z.string().optional(),
  preparation_checklist: jsonSchema.optional().nullable(),
  risk_score: z.number().optional().nullable(),
  summary: z.string().optional().nullable(),
  triage_level: z.string().optional().nullable(),
});

export const publicAiReportsUpdateSchema = z.object({
  created_at: z.string().optional().nullable(),
  emergency_id: z.string().optional().nullable(),
  id: z.string().optional(),
  preparation_checklist: jsonSchema.optional().nullable(),
  risk_score: z.number().optional().nullable(),
  summary: z.string().optional().nullable(),
  triage_level: z.string().optional().nullable(),
});

export const publicAiReportsRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("ai_reports_emergency_id_fkey"),
    columns: z.tuple([z.literal("emergency_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("emergencies"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicDoctorsRowSchema = z.object({
  created_at: z.string().nullable(),
  hospital_id: z.string().nullable(),
  id: z.string(),
  name: z.string().nullable(),
  specialization: z.string().nullable(),
});

export const publicDoctorsInsertSchema = z.object({
  created_at: z.string().optional().nullable(),
  hospital_id: z.string().optional().nullable(),
  id: z.string(),
  name: z.string().optional().nullable(),
  specialization: z.string().optional().nullable(),
});

export const publicDoctorsUpdateSchema = z.object({
  created_at: z.string().optional().nullable(),
  hospital_id: z.string().optional().nullable(),
  id: z.string().optional(),
  name: z.string().optional().nullable(),
  specialization: z.string().optional().nullable(),
});

export const publicDoctorsRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("doctors_hospital_id_fkey"),
    columns: z.tuple([z.literal("hospital_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("hospitals"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("doctors_id_fkey"),
    columns: z.tuple([z.literal("id")]),
    isOneToOne: z.literal(true),
    referencedRelation: z.literal("profiles"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicEmergenciesRowSchema = z.object({
  created_at: z.string().nullable(),
  eta_minutes: z.number().nullable(),
  hospital_id: z.string().nullable(),
  id: z.string(),
  patient_id: z.string().nullable(),
  risk_score: z.number().nullable(),
  status: z.string(),
  triage_level: z.string().nullable(),
  updated_at: z.string().nullable(),
});

export const publicEmergenciesInsertSchema = z.object({
  created_at: z.string().optional().nullable(),
  eta_minutes: z.number().optional().nullable(),
  hospital_id: z.string().optional().nullable(),
  id: z.string().optional(),
  patient_id: z.string().optional().nullable(),
  risk_score: z.number().optional().nullable(),
  status: z.string(),
  triage_level: z.string().optional().nullable(),
  updated_at: z.string().optional().nullable(),
});

export const publicEmergenciesUpdateSchema = z.object({
  created_at: z.string().optional().nullable(),
  eta_minutes: z.number().optional().nullable(),
  hospital_id: z.string().optional().nullable(),
  id: z.string().optional(),
  patient_id: z.string().optional().nullable(),
  risk_score: z.number().optional().nullable(),
  status: z.string().optional(),
  triage_level: z.string().optional().nullable(),
  updated_at: z.string().optional().nullable(),
});

export const publicEmergenciesRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("emergencies_hospital_id_fkey"),
    columns: z.tuple([z.literal("hospital_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("hospitals"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("emergencies_patient_id_fkey"),
    columns: z.tuple([z.literal("patient_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("patients"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicHospitalsRowSchema = z.object({
  address: z.string().nullable(),
  created_at: z.string().nullable(),
  id: z.string(),
  latitude: z.number().nullable(),
  longitude: z.number().nullable(),
  name: z.string(),
});

export const publicHospitalsInsertSchema = z.object({
  address: z.string().optional().nullable(),
  created_at: z.string().optional().nullable(),
  id: z.string().optional(),
  latitude: z.number().optional().nullable(),
  longitude: z.number().optional().nullable(),
  name: z.string(),
});

export const publicHospitalsUpdateSchema = z.object({
  address: z.string().optional().nullable(),
  created_at: z.string().optional().nullable(),
  id: z.string().optional(),
  latitude: z.number().optional().nullable(),
  longitude: z.number().optional().nullable(),
  name: z.string().optional(),
});

export const publicPatientsRowSchema = z.object({
  age: z.number().nullable(),
  created_at: z.string().nullable(),
  gender: z.string().nullable(),
  id: z.string(),
  insurance_id: z.string().nullable(),
  is_insured: z.boolean().nullable(),
  is_unknown: z.boolean().nullable(),
});

export const publicPatientsInsertSchema = z.object({
  age: z.number().optional().nullable(),
  created_at: z.string().optional().nullable(),
  gender: z.string().optional().nullable(),
  id: z.string(),
  insurance_id: z.string().optional().nullable(),
  is_insured: z.boolean().optional().nullable(),
  is_unknown: z.boolean().optional().nullable(),
});

export const publicPatientsUpdateSchema = z.object({
  age: z.number().optional().nullable(),
  created_at: z.string().optional().nullable(),
  gender: z.string().optional().nullable(),
  id: z.string().optional(),
  insurance_id: z.string().optional().nullable(),
  is_insured: z.boolean().optional().nullable(),
  is_unknown: z.boolean().optional().nullable(),
});

export const publicPatientsRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("patients_id_fkey"),
    columns: z.tuple([z.literal("id")]),
    isOneToOne: z.literal(true),
    referencedRelation: z.literal("profiles"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicProfilesRowSchema = z.object({
  created_at: z.string().nullable(),
  full_name: z.string().nullable(),
  id: z.string(),
  role: z.string(),
});

export const publicProfilesInsertSchema = z.object({
  created_at: z.string().optional().nullable(),
  full_name: z.string().optional().nullable(),
  id: z.string(),
  role: z.string(),
});

export const publicProfilesUpdateSchema = z.object({
  created_at: z.string().optional().nullable(),
  full_name: z.string().optional().nullable(),
  id: z.string().optional(),
  role: z.string().optional(),
});

export const publicSymptomsRowSchema = z.object({
  chief_complaint: z.string().nullable(),
  created_at: z.string().nullable(),
  doctor_observations: z.string().nullable(),
  emergency_id: z.string().nullable(),
  id: z.string(),
});

export const publicSymptomsInsertSchema = z.object({
  chief_complaint: z.string().optional().nullable(),
  created_at: z.string().optional().nullable(),
  doctor_observations: z.string().optional().nullable(),
  emergency_id: z.string().optional().nullable(),
  id: z.string().optional(),
});

export const publicSymptomsUpdateSchema = z.object({
  chief_complaint: z.string().optional().nullable(),
  created_at: z.string().optional().nullable(),
  doctor_observations: z.string().optional().nullable(),
  emergency_id: z.string().optional().nullable(),
  id: z.string().optional(),
});

export const publicSymptomsRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("symptoms_emergency_id_fkey"),
    columns: z.tuple([z.literal("emergency_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("emergencies"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicVideoCallParticipantsRowSchema = z.object({
  created_at: z.string().nullable(),
  id: z.string(),
  joined_at: z.string().nullable(),
  left_at: z.string().nullable(),
  profile_id: z.string().nullable(),
  role: z.string().nullable(),
  video_call_id: z.string().nullable(),
});

export const publicVideoCallParticipantsInsertSchema = z.object({
  created_at: z.string().optional().nullable(),
  id: z.string().optional(),
  joined_at: z.string().optional().nullable(),
  left_at: z.string().optional().nullable(),
  profile_id: z.string().optional().nullable(),
  role: z.string().optional().nullable(),
  video_call_id: z.string().optional().nullable(),
});

export const publicVideoCallParticipantsUpdateSchema = z.object({
  created_at: z.string().optional().nullable(),
  id: z.string().optional(),
  joined_at: z.string().optional().nullable(),
  left_at: z.string().optional().nullable(),
  profile_id: z.string().optional().nullable(),
  role: z.string().optional().nullable(),
  video_call_id: z.string().optional().nullable(),
});

export const publicVideoCallParticipantsRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("video_call_participants_profile_id_fkey"),
    columns: z.tuple([z.literal("profile_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("profiles"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("video_call_participants_video_call_id_fkey"),
    columns: z.tuple([z.literal("video_call_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("video_calls"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicVideoCallsRowSchema = z.object({
  created_at: z.string().nullable(),
  emergency_id: z.string().nullable(),
  ended_at: z.string().nullable(),
  id: z.string(),
  room_name: z.string(),
  started_at: z.string().nullable(),
  status: z.string().nullable(),
});

export const publicVideoCallsInsertSchema = z.object({
  created_at: z.string().optional().nullable(),
  emergency_id: z.string().optional().nullable(),
  ended_at: z.string().optional().nullable(),
  id: z.string().optional(),
  room_name: z.string(),
  started_at: z.string().optional().nullable(),
  status: z.string().optional().nullable(),
});

export const publicVideoCallsUpdateSchema = z.object({
  created_at: z.string().optional().nullable(),
  emergency_id: z.string().optional().nullable(),
  ended_at: z.string().optional().nullable(),
  id: z.string().optional(),
  room_name: z.string().optional(),
  started_at: z.string().optional().nullable(),
  status: z.string().optional().nullable(),
});

export const publicVideoCallsRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("video_calls_emergency_id_fkey"),
    columns: z.tuple([z.literal("emergency_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("emergencies"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicVitalsRowSchema = z.object({
  blood_sugar: z.number().nullable(),
  diastolic_bp: z.number().nullable(),
  emergency_id: z.string().nullable(),
  heart_rate: z.number().nullable(),
  id: z.string(),
  oxygen_saturation: z.number().nullable(),
  recorded_at: z.string().nullable(),
  systolic_bp: z.number().nullable(),
});

export const publicVitalsInsertSchema = z.object({
  blood_sugar: z.number().optional().nullable(),
  diastolic_bp: z.number().optional().nullable(),
  emergency_id: z.string().optional().nullable(),
  heart_rate: z.number().optional().nullable(),
  id: z.string().optional(),
  oxygen_saturation: z.number().optional().nullable(),
  recorded_at: z.string().optional().nullable(),
  systolic_bp: z.number().optional().nullable(),
});

export const publicVitalsUpdateSchema = z.object({
  blood_sugar: z.number().optional().nullable(),
  diastolic_bp: z.number().optional().nullable(),
  emergency_id: z.string().optional().nullable(),
  heart_rate: z.number().optional().nullable(),
  id: z.string().optional(),
  oxygen_saturation: z.number().optional().nullable(),
  recorded_at: z.string().optional().nullable(),
  systolic_bp: z.number().optional().nullable(),
});

export const publicVitalsRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("vitals_emergency_id_fkey"),
    columns: z.tuple([z.literal("emergency_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("emergencies"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export type Json = z.infer<typeof jsonSchema>;
export type PublicAiReportsRow = z.infer<typeof publicAiReportsRowSchema>;
export type PublicAiReportsInsert = z.infer<typeof publicAiReportsInsertSchema>;
export type PublicAiReportsUpdate = z.infer<typeof publicAiReportsUpdateSchema>;
export type PublicAiReportsRelationships = z.infer<
  typeof publicAiReportsRelationshipsSchema
>;
export type PublicDoctorsRow = z.infer<typeof publicDoctorsRowSchema>;
export type PublicDoctorsInsert = z.infer<typeof publicDoctorsInsertSchema>;
export type PublicDoctorsUpdate = z.infer<typeof publicDoctorsUpdateSchema>;
export type PublicDoctorsRelationships = z.infer<
  typeof publicDoctorsRelationshipsSchema
>;
export type PublicEmergenciesRow = z.infer<typeof publicEmergenciesRowSchema>;
export type PublicEmergenciesInsert = z.infer<
  typeof publicEmergenciesInsertSchema
>;
export type PublicEmergenciesUpdate = z.infer<
  typeof publicEmergenciesUpdateSchema
>;
export type PublicEmergenciesRelationships = z.infer<
  typeof publicEmergenciesRelationshipsSchema
>;
export type PublicHospitalsRow = z.infer<typeof publicHospitalsRowSchema>;
export type PublicHospitalsInsert = z.infer<typeof publicHospitalsInsertSchema>;
export type PublicHospitalsUpdate = z.infer<typeof publicHospitalsUpdateSchema>;
export type PublicPatientsRow = z.infer<typeof publicPatientsRowSchema>;
export type PublicPatientsInsert = z.infer<typeof publicPatientsInsertSchema>;
export type PublicPatientsUpdate = z.infer<typeof publicPatientsUpdateSchema>;
export type PublicPatientsRelationships = z.infer<
  typeof publicPatientsRelationshipsSchema
>;
export type PublicProfilesRow = z.infer<typeof publicProfilesRowSchema>;
export type PublicProfilesInsert = z.infer<typeof publicProfilesInsertSchema>;
export type PublicProfilesUpdate = z.infer<typeof publicProfilesUpdateSchema>;
export type PublicSymptomsRow = z.infer<typeof publicSymptomsRowSchema>;
export type PublicSymptomsInsert = z.infer<typeof publicSymptomsInsertSchema>;
export type PublicSymptomsUpdate = z.infer<typeof publicSymptomsUpdateSchema>;
export type PublicSymptomsRelationships = z.infer<
  typeof publicSymptomsRelationshipsSchema
>;
export type PublicVideoCallParticipantsRow = z.infer<
  typeof publicVideoCallParticipantsRowSchema
>;
export type PublicVideoCallParticipantsInsert = z.infer<
  typeof publicVideoCallParticipantsInsertSchema
>;
export type PublicVideoCallParticipantsUpdate = z.infer<
  typeof publicVideoCallParticipantsUpdateSchema
>;
export type PublicVideoCallParticipantsRelationships = z.infer<
  typeof publicVideoCallParticipantsRelationshipsSchema
>;
export type PublicVideoCallsRow = z.infer<typeof publicVideoCallsRowSchema>;
export type PublicVideoCallsInsert = z.infer<
  typeof publicVideoCallsInsertSchema
>;
export type PublicVideoCallsUpdate = z.infer<
  typeof publicVideoCallsUpdateSchema
>;
export type PublicVideoCallsRelationships = z.infer<
  typeof publicVideoCallsRelationshipsSchema
>;
export type PublicVitalsRow = z.infer<typeof publicVitalsRowSchema>;
export type PublicVitalsInsert = z.infer<typeof publicVitalsInsertSchema>;
export type PublicVitalsUpdate = z.infer<typeof publicVitalsUpdateSchema>;
export type PublicVitalsRelationships = z.infer<
  typeof publicVitalsRelationshipsSchema
>;
